version: '3.8'
services:
  webserver:
    platform: linux/amd64
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: eorjs37/nginx-practice
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge
